[DROPDOWN] added dropdown menu for product display
Christina-Wang-Capstone-Project/foodwaste-project pull request #9
Opened 2022-08-03 21:18 UTC by cwang12197

##ADDED DROPDOWN MENU IN HOME PAGE 

- enable users to sort display of products by distance close to far, distance far to close, newest arrivals (posts that have been created recently), and about to expire 
- works in tangent to setting location range 
- fixed Parse database where storing distance as a String instead of a Number 

TESTPLAN

2022-08-03 22:44 UTC, cwang12197 commented
##FIXED UI STYLING

- got rid of grey padding on sidebar (due to overflow: scroll) 
- expanded length of search input in search bar 
- changed quantity variable storage format from String to Number 

TESTPLAN
This shows the website successfully compiling after these edits:
<img width="418" alt="Screen Shot 2022-08-03 at 3 41 57 PM" src="https://user-images.githubusercontent.com/68706299/182725014-37bc37f3-ecf3-4e33-b293-571684a099d5.png">

2022-08-03 22:49 UTC, cwang12197 commented
##ADDED UNIT TESTING TO NEW DROPDOWN FEATURE 

- conduct unit testing on axios get requests 
<img width="940" alt="Screen Shot 2022-08-03 at 3 48 16 PM" src="https://user-images.githubusercontent.com/68706299/182725693-f57ea31e-265d-45f4-b744-02b480fe5ab5.png">

2022-08-03 23:23 UTC, jennyhan1999 commented on food-waste-express-api/__tests__/sortProductsByDropdownMenu.js
> +                expect(res.data.length > 0) // expect return.length > 0
delete the comment on these, self explanatory

2022-08-03 23:24 UTC, jennyhan1999 commented on food-waste-express-api/__tests__/sortProductsByDropdownMenu.js
> +        test('SortProductTest', () => {
What is the difference between each of these 'test('SortProductTest',' ? Can we label these better or reduce it to just 1 if they are similar?

2022-08-03 23:26 UTC, jennyhan1999 commented on food-waste-express-api/routes/dropdown.js
> +    if (dropdownOption == 0) {
another option is to case on dropdownOption rather than doing so many else ifs

2022-08-03 23:28 UTC, jennyhan1999 commented on food-waste-express-api/__tests__/sortProductsByDropdownMenu.js
> +        test('SortProductTest', () => {
I see, seems like these are different sort methods. 
1. label these something like sortProductListByDistanceHighToLowTest
2. Checking if the return length is not as valuable of a test as checking to make sure that the ordering is correct. In the case of sortProductListByDistanceHighToLowTest, make sure to loop through the products to ensure the distance is actually set from high to low etc.

2022-08-03 23:29 UTC, jennyhan1999 requested changes
fix tests

2022-08-04 03:23 UTC, cwang12197 commented
##FIXED DROPDOWN UNIT TESTS 

- loops through to check order of list of products based on dropdown menu
TESTPLAN
<img width="939" alt="Screen Shot 2022-08-03 at 8 20 41 PM" src="https://user-images.githubusercontent.com/68706299/182756180-1dd3035b-4829-4804-84de-4fb30eb1e0c3.png">

2022-08-04 03:40 UTC, jennyhan1999 approved these changes
lgtm

2022-08-04 03:59 UTC, merged